### ISSUE TITLE
Move the file to indent subfolder

### ISSUE THREAD

**Issue by winged** [ganwell/rst.vim#1]
Please move the file into a subfilder named "indent".
If you move the file to the "indent" subfolder, this repo becomes installable via any of the plugin managers, such as Vundle, VimPlug etc, as it will have the same "common" structure.

**Comment by ganwell** [comment]
@winged But it is in the folder ftplugin on my system?? And it is not about identing? Sorry I don't get all this vim folder magic. I'll try what happens, but then I have to factor out the ftplugin-style settings.

**Comment by winged** [comment]
Sorry, yes the "indent" is wrong of course. So "ftplugin" should be correct.
Plugin managers expect that the plugin folder structure is the same as for your "regular" ~/.vim

**Comment by ganwell** [comment]
@winged indent works ftplugin does not, shall I leave it there?

**Comment by ganwell** [comment]
@winged the code is actually read if put it into ftplugin, but all kind of strange things happen.

**Comment by ganwell** [comment]
@winged Move it, but had to remove the echo from parse(), because it caused a press enter when the script was in ftplugin.

**Comment by ganwell** [comment]
According to our real world discussion I close this.
